name: rExpLevel
version: '1.0'
main: ru.truhot.rexplevel.RExpLevel
api-version: '1.21.4'
folia-supported: true
authors: [Truhot]
softdepend: [PlaceholderAPI]

libraries:
  - com.zaxxer:HikariCP:7.1.0
  - com.j256.ormlite:ormlite-jdbc:6.1
  - org.xerial:sqlite-jdbc:3.53.2.1
